### ISSUE TITLE
Feature list

### ISSUE THREAD

**Issue by shiba24** [open-neuromorphic/expelliarmus#2]
Hi, thanks for the library and I'm very up for contributing. I think this is important for people working on the `.raw` data.

Do you have any list of functionalities to implement? For example, I have a couple:

- convert raw to hdf5 file (I have a script from .raw to .hdf5 using metavision_sdk python)
- seek_event equivalent (our team has faced some bugs related to seek_event and so on: https://github.com/prophesee-ai/openeb/issues/61)
- Documentation

I have been working on many datasets (DAVIS from ETH, MVSEC, DSEC, IROS-EED, etc...) in python for research.
In my opinion, the Muggle is better general use-case, because usually the data is large and Wizard does not work (in many research use-cases). (That's why I have hdf5 conversion script, btw.)
And enabling sort of random access to events, not only iterator-based one, is very important for R&D usecases.

But I'd like to make sure that we are aligned first.

Best,
Shintaro

**Comment by biphasic** [comment]
Hey @shiba24,
thanks for suggesting to help. I'd like to understand your use cases better. 

Regarding your first point, could you explain to me why you would like to convert to hdf5? Is it that you store chunks of the original data in separate hdf5 files, judging from your Muggle comment?
Have you had a chance to look at [Tonic] by any chance? It has support for data slicing and does exactly that. It loads whole files using expelliarmus and then store chunks of it (which we call caching) in hdf5.

Regarding your second point, my assumption is that seek_event allows you to jump to a specific event in a sample and then read from there. When do you use that in practice and how is it different than the second point?

**Comment by shiba24** [comment]
Documentation - I agree that it is low-prioritized at this moment.

Let me explain the very abstract level. I want to use every data loader something like this:

```
loader.load_event(i1, i2)     # returns array (or equivalent) of events, size (i2 - i1, 4).
loader.num_events             # or len(loader), returns the total number of events
loader.duration               # or whatever, returns the total duration of data in seconds.
loader.index_to_time(i)       # returns timestamp
loader.time_to_index(t)       # returns the nearest (or the last) event index
```

And, as a user I don't want to take care of multiple small files, or directory structure that has multiple files. 
I would like to specify always one single file to load.
The reasons, and my thoughts when I implemented my data loader for other datasets are in below.

0. The reason for single-file, not splitting into separate files
- If you split the files, the loader program becomes more complex, handling many edge-cases.
- For example, if `i1` is in file1 and `i2` is in file2.
- So you need to implement the logic to get the metadata (how long is each chunk file etc) somewhere else.
- This might be also buggy if you want to share data with others.
- Also after I destruct and construct another data_loader class instance with the same original data file, it's not easy to maintain the compatibility and reproduceability.

Well, to be fair, the API implementation is still possible with chunking the file into multiple.
But I think the implementation becomes much complex.

1. The reason that I use HDF5 file:
 - (I cannot use metavision_sdk on Mac so needed to convert it using Ubuntu, that was the first point for me...)
 - HDF5 file does not require to load all the file contents onto the memory, and still it can achieve the above API.
 - So, you can implement the above _without_ splitting into multiple files.

2. `seek_event`
- This is, basically, for the API above. I needed `seek_event` equivalent logic for `index_to_time`. Also I needed something similar for `time_to_index` logic (it costs O(Nlog(N) for N number of events in data).
- Well, my hidden assumption was that you can load the timestamp numpy array (only the timestamps, not x,y,p) into the memory to run the search.

All the things are possible if you load events at once into the memory (`Wizard`) -> you can handle if it is a numpy array.


Answering the question of @biphasic 

> could you explain to me why you would like to convert to hdf5?

If something like the above APIs is possible without hdf5 file, I actually don't need to.
Then, it's more a utility (optional) function for people to use. (nice to have, for compatibility)

> Tonic

Didn't know it, and will take a look at it later.
Thanks :)

**Comment by fabhertz95** [comment]
Okay, I think I got you point.
- For what regards HDF5, you can write it to disk in chunks using `Muggle` pretty easily, I think. For sure I can easily provide a `Muggle` method that does it, if you want too, but then `expelliarmus` would be dependent on `h5py`. I think that you can do it in the following way.
```python
from expelliarmus import Muggle
import h5py
h5_file = h5py.File("./evt3_to_HDF5.hdf5")
muggle = Muggle(encoding="evt3")

# First run to estimate how long is the array.
arr_len = 0
for chunk_arr in muggle.read_chunk("./evt3_file.raw", nevents_per_chunk=2048):
    arr_len += len(chunk_arr)

# Creating the array in the HDF5 file.
arr = h5_file.create_dataset("arr", (arr_len,), muggle._dtype)
muggle = Muggle(encoding="evt3")
chunk_offset=0
for chunk_arr in muggle.read_chunk("./evt3_file.raw", nevents_per_chunk=2048):
    arr[chunk_offset:min(chunk_offset+len(chunk_arr), arr_len)] = chunk_arr[:]
    chunk_offset += len(chunk_arr)
```

- Usually datasets are split in multiple files, one for each recording. That's why we don't see how `seek_event` can be useful but, again, one can build something on top of `Muggle` to achieve it.

**Comment by fabhertz95** [comment]
Hi @shiba24, we have added a new feature: time window batching. You can find it on the develop branch. It allows to specify a time window in milliseconds and to read the events in windows of the duration specified. 

We were interested in adding a save feature to the code. Right now, it is possible to save a NumPy array to EVT2, allowing data compression without compromising read speed. We wanted to do the same for EVT3. Would you be interested in contributing for this feature?

**Comment by shiba24** [comment]
@fabhertz95 Thank you, I'm interested, but busy with some errands now - I don't want to block you by holding tasks, so please feel free to proceed 🙏  I keep watching the repo and let you know I'm more available!

**Comment by shiba24** [comment]
Hello, sorry I was busy, but now have some time to try it by myself.
Let me close the issue because it becomes stale -- I wrote a conversion script from EVT3 to HDF5. It's working perfectly.


```
import logging

import h5py
from tqdm import tqdm
from expelliarmus import Wizard

logger = logging.getLogger(__name__)


def convert_evt3_to_hdf5(evt3file: str, hdf5file: str):
    """Convert EVT3 data format into HDF5 format.

    Args:
        evt3file (str): file path for the EVT3 file
        hdf5file (str): file path for the HDF5 file
    """
    wizard = Wizard(encoding="evt3", fpath=evt3file, chunk_size=16384)
    logger.info(f"Convert Prophesee data {evt3file}")
    logger.info(f"Saving events into {hdf5file}")
    i = 0
    with h5py.File(hdf5file, "w") as f:
        for events in tqdm(wizard.read_chunk()):
            if i == 0:
                f.create_dataset(
                    "raw_events/x",
                    data=events["x"],
                    maxshape=(None,),
                    compression="gzip",
                    compression_opts=9,
                )
                f.create_dataset(
                    "raw_events/y",
                    data=events["y"],
                    maxshape=(None,),
                    compression="gzip",
                    compression_opts=9,
                )
                f.create_dataset(
                    "raw_events/t",
                    data=events["t"],
                    maxshape=(None,),
                    compression="gzip",
                    compression_opts=9,
                )
                f.create_dataset(
                    "raw_events/p",
                    data=events["p"],
                    maxshape=(None,),
                    compression="gzip",
                    compression_opts=9,
                )
            else:
                hdf5append(f["raw_events/x"], events["x"])
                hdf5append(f["raw_events/y"], events["y"])
                hdf5append(f["raw_events/t"], events["t"])
                hdf5append(f["raw_events/p"], events["p"])
            i += len(events)
    logger.info(f"Done. Total {i} events are processed.")


def hdf5append(data, new_arr):
    n_old = data.shape[0]
    n_new = n_old + len(new_arr)
    data.resize(n_new, axis=0)
    data[n_old:] = new_arr
```

**Comment by fabrizio-ottati** [comment]
In the issues you can find some! The most significative right now is the EVT3 conversion, which is not fully optimised right now (I was too lazy to vectorize events). I am working separately on a C++ version of expelliarmus to improve code reusability and to make it easier to extend and maintain it, but it still performs worse than the original C code.
